FROM docker.io/library/python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY deploy/rhel9/offline/wheels/api-py312-linux-amd64 /wheels
COPY apps/api/requirements.txt /app/requirements.txt
RUN python3.12 -m pip install --no-index --find-links /wheels -r /app/requirements.txt

COPY apps/api/app /app/app
COPY configs /app/configs

RUN mkdir -p /app/storage

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
